# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3cf5b10ea6082c151142bd778ed65d645179a18c62938d28c6a19a03dc8230465607ac5c27e621901790a85f8b6a96c308771adfd72bb617b12b7dc53b7a27fb

test:
  secret_key_base: 1880695476e18bf19201acc08e11f9616e41ddd1c7f0deec55a6186923a0ada49a0d8757ef2c3ef42dc8c55118ef40c41968b3325b705fca631eb44e08225e51

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
